### ISSUE TITLE
Error occurred while executing command 'papi i player' for source DedicatedServer: null

### ISSUE THREAD

**Issue by ziceptor** [rojo8399/PlaceholderAPI#13]
/papi i player

http://pastebin.com/Ed9dd1eg

forge-1.11.2-13.20.0.2227-universal.jar
spongeforge-1.11.2-2227-6.0.0-BETA-2148.jar
Placeholders-3.0.jar

**Comment by Wundero** [comment]
Fixed in version 3.1.
