### ISSUE TITLE
java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by ziceptor** [rojo8399/PlaceholderAPI#14]
SpongeAPI version: spongeforge-1.11.2-2227-6.0.0-BETA-2157.jar

PlaceholderAPI version: Placeholders-3.4.jar

Plugins installed:
AntiWDL-1.1-all.jar
API6-BetterBoom.jar
AutoBroadcasterSponge-0.2.1.jar
CommandSigns-API-6.0.0-1.3.1.jar
CustomPlayerCount.-.1.1.jar
EasyScoreboards.jar!
EconomyLite-5.0.0-2.9.0.jar
FlexibleLogin.jar
foxcore-0.10.3-208-server.jar
foxguard-0.20.2-api5-347-server.jar
Graveyards-v2.1.3.jar
helpme-5.0.0-0.2.2.jar
holograms-2.1.1.jar
IPLog-0.1.1.jar
JobsLite-1.7.0.jar
Launchpad-v1.0-FIXED.jar
MiscStuff-1.0-SNAPSHOT.jar
Nucleus-0.23.2-1.11.2-S6.0-plugin.jar
ore-plugin-1.1.0-SNAPSHOT.jar
PermissionsEx-Sponge.jar
Placeholders-3.4.jar
projectportals-5.1.0-0.13.6.jar
spongeforge-1.11.2-2227-6.0.0-BETA-2157.jar
Synonym-1.0.1.jar
TitleMOTD.-.1.0.jar
treepers-5.1.3.jar
twentyticks.jar
Vigilate-1.0.2.jar
walletdrop-5.1.0-0.2.1.jar
worldedit-sponge-6.1.7-SNAPSHOT-dist.jar

Error log [if any]: http://pastebin.com/EywHhmLh

Description: 

Steps to reproduce: First start the server, after upgrading the plugin

**Comment by dualspiral** [comment]
<s>That's a problem with Sponge.</s>

Actually, while I think sponge should handle this better, the world isn't loaded yet so data cannot be read. You need to delay your sync operation until later, probably until worlds are loaded (though you might be able to go earlier, just not pre-init) - [based on the lifecylce document](https://docs.spongepowered.org/stable/en-GB/plugin/lifecycle.html?highlight=lifecycle#running-states), you want `GameStartingServerEvent`.

**Comment by Wundero** [comment]
Fixed by 17d6184 and 0c78488.
