### ISSUE TITLE
What is wrong with my code?

### ISSUE THREAD

**Issue by jonas-peeters** [rojo8399/PlaceholderAPI#16]
## Versions
SpongeAPI version: 5.1.0-BETA-370

PlaceholderAPI version: 3.7

## Problem
Hi,
Here is the dev of EasyScoreboards.
This is the code I am currently trying to use, however the only thing it prints is `%player%`.

    Optional<PlaceholderService> service = Sponge.getGame().getServiceManager().provide(PlaceholderService.class);
    if (service.isPresent()) {
        PlaceholderService placeholderService = service.get();
        System.out.println(placeholderService.replacePlaceholdersLegacy(player, "%player%", "%", "%"));
    }

Any idea what could be wrong with that. There is no error message or anything else.

Thanks in advance

**Comment by Wundero** [comment]
Have you enabled the `player` placeholder in your PlaceholderAPI configuration?

**Comment by Wundero** [comment]
Also, you need not specify the `%` `%` at the end because those are provided by default when not specified.

**Comment by jonas-peeters** [comment]
Player is enabled. Here is my config:

    expansions {
        player = true
        server = true
        sound = false
        rank = false
        economy = true
        javascript = false
        time {
            enabled = true
            format = "uuuu MMM dd HH:mm:ss"
        }
    }

I just added the `%`-part to make sure that this is not the problem.

**Comment by Wundero** [comment]
Alright I will look into this. I have not personally tested `replacePlaceholdersLegacy` yet which might be the problem.

**Comment by Wundero** [comment]
I figured out what the problem is and I will push a fix for it as soon as I can.

**Comment by jonas-peeters** [comment]
Great to hear that. Thanks a lot

**Comment by Wundero** [comment]
Ok with version 3.8 (I will put it on Ore in a minute) it should work, I have run unit tests to confirm but if it breaks I will reopen the issue.
