### ISSUE TITLE
Allow applying own TextTemplate params

### ISSUE THREAD

**Issue by randombyte-developer** [rojo8399/PlaceholderAPI#17]
There is `Text replacePlaceholders(Player player, TextTemplate text)` for `TextTemplate`s. I would like to apply my own parameters additionally to the ones from PlayeholderAPI.
How about a method that allows additional params to be passed to the TextTemplate. Or the PlaceholderAPI returns a map of the filled in params and values that the plugin using PAPI applies itself on the TextTemplate?

**Comment by Wundero** [comment]
I actually thought TextTemplate allowed you to add your own placeholders to it without building but I was mistaken. Version 3.8 will support both providing your own to PlaceholderAPI and getting what PlaceholderAPI would use for a template.
