### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ziceptor** [rojo8399/PlaceholderAPI#19]
Is it possible to add the direction of the player? North, South, West, East, intermediate.

**Comment by Wundero** [comment]
I will look into adding it.

**Comment by Wundero** [comment]
It will be added in version 3.10.

**Comment by Wundero** [comment]
Added in 3.10 with `%player_direction%` (Shows North, Northeast, East, Southeast, South, Southwest, West, Northwest cardinal directions).

**Comment by ziceptor** [comment]
Thank you! It will be possible to translate into other languages?

**Comment by Wundero** [comment]
I will look into adding localization support.
