### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Wundero** [rojo8399/PlaceholderAPI#20]
I need to create a license for this plugin and put it in all of the files. I will be using the MIT license. I am unsure as to who (or what group/org) to denote it under but I will likely go with rojo8399. Any thoughts would be appreciated.

**Comment by ronaldburns** [comment]
If it doesn't matter the plugins under me in sponge (or if we can give it to you) go ahead and put it under your name. I only started the project. You did most of the work making it the awesome plugin it is today.

**Comment by Wundero** [comment]
Alright, I will license it under my username.

**Comment by Wundero** [comment]
Most classes should be licensed at this point, no need to keep this issue open.
