### ISSUE TITLE
Getting the message receiver

### ISSUE THREAD

**Issue by jayoevans** [rojo8399/PlaceholderAPI#21]
Simply put, when creating an Expansion, you have the onPlaceholderRequest(Player, Identifier) method. The player obviously is the player who is writing the message. I am wondering if it's possible to get the person looking at the message, so that the format can be modified based on the relationship the players have? This all depends on how messages are sent obviously, and if there are any limitations preventing this. I'm using PlaceholderAPI along with DeluxeChat, and am wanting to have a placeholder for the colour relationship between two factions players (ally faction tags are green, enemy are red). I believe you could do this in the past with %faction_relation_color%, or something similar, however I've not been able to get it working.

A solution to either/both would be much appreciated! :)

**Comment by Wundero** [comment]
Well I should mention first that this version of PlaceholderAPI is exclusive to the SpongeAPI project, while DeluxeChat, and the PlaceholderAPI that it uses, are for Spigot. For relational placeholders in DeluxeChat, install [this](https://www.spigotmc.org/resources/placeholderapi.6245/) instead.

As far as relational placeholders in this plugin are concerned, I have actually been working on them for a little while now, and am almost at a point where I can release them. Of course, they will need time to be used as hooks, but I am making them nonetheless. Through the process of making the new API I discovered that I would like to change the API that I currently use but I cannot do that without breaking existing expansions, so I will not be changing that. I should be able to get relational placeholders (the method to use one, by the way, would be `onRelationalRequest(Player one, Player two, Optional<String> identifier)`) out within the next couple of days.

**Comment by jayoevans** [comment]
That's fantastic to hear! Sorry for posting this in the wrong section though. Thank you for your response, this is very useful information. Best of luck with the development <3
