### ISSUE TITLE
Wiki updates

### ISSUE THREAD

**Issue by Wundero** [rojo8399/PlaceholderAPI#22]
This is a collection of things I need to update on the wiki due to changes in the plugin.
- [x] Annotated placeholders
  - How to write a method that supports placeholders (public class AND method, params must be of supported types or higher level)
  - What every annotation (Source, Observer, Token, Nullable, Relational) does
  - Best practices
- [x] Expansion builder
  - How to use this in conjunction with annotated classes
  - How to create simple function-based placeholders
  - What each method does
  - What `ExpansionFunction` is and does
- [x] New `PlaceholderService` methods
  - builder, load, loadAll, registerExpansion, isRegistered
  - fillPlaceholders, parse, fill, parseNullable, replacePlaceholders
  - getDefaultPattern, verifySource, verifyObserver
- [x] Update placeholders list
- [x] JavaScript placeholders with example + explain for `value`
- [x] Parse command with relational support
- [x] General cleanup

**Comment by Sir-Will** [comment]
Any news to this? Just wanted to create a expansion but then found out that the wiki is outdated :/

**Comment by Wundero** [comment]
Updated the wiki for version 4.2, which should come out shortly.
