### ISSUE TITLE
Correct commit to use in plugins that add support for PlaceholderAPI

### ISSUE THREAD

**Issue by randombyte-developer** [rojo8399/PlaceholderAPI#26]
So it might be confusing for developers that don't know jitpack what the line `compile "com.github.rojo8399:PlaceholderAPI:master-SNAPSHOT"` does.

I just wanted to add support in another plugin for PAPI but looking at the current commits it may be not working with the latest commit of master(`SNAPSHOT`). So I had to dig to the commit that introduced version 4.0 and use that. I would very really highly recommend you to just add a version tag under the release section of this repo to point to this commit of v4.0. Then the dependency looks like this: `com.github.rojo8399:PlaceholderAPI:v4.0`. It would make things very easy.

I do this regularly: https://github.com/randombyte-developer/kosp/tags

Edit: 1b6fb7bf6c5adccaae8e240fd2ea84da5d7e5d8b is right for 4.0?

**Comment by Wundero** [comment]
Nope, that commit is not version 4.0. Version 3.12 is likely what you are looking for if you don't want to work with the breaking changes. 4.0 is the complete rewrite to support more than player, annotation based object-method registration and more nifty stuff. Version 3.12 will be kept on the branch [legacy-(3.12)](https://github.com/rojo8399/PlaceholderAPI/tree/legacy-(3.12)) for some time, for documentation and legacy support purposes. 

To clarify: version 4.0 was SUPPOSED to be the update adding relational placeholders and forcing a breaking method change. However, a suggestion by dualspiral got me thinking about a more effective system to have more dynamic replacement. As such, I moved the then-existing 4.0 into 3.12 and undid it's breaking change, then completely rewrote the plugin, and called the new version 4.0. (Sorry for the confusion about this).

I will look into release tags for jitpack for both 3.12 and 4.0, and all future versions. Shouldn't be too hard to do so I will likely do it by the release of 4.0.

**Comment by randombyte-developer** [comment]
Ok, thanks. Creating a tag/release is very easy: releases -> new -> pick right commit on right branch -> name the thing(v3.12) -> done!

**Comment by Wundero** [comment]
Tags exist for 3.12, 4.0 and 4.1. Any future versions will also have tags attached to them.
