### ISSUE TITLE
Separate API/service from plugin

### ISSUE THREAD

**Issue by randombyte-developer** [rojo8399/PlaceholderAPI#27]
I suggest separating the pure API/PlaceholderSercive from the real plugin. Then the dependency would look like this: `com.github.rojo8399.PlaceholderAPI:api:SNAPSHOT` or `com.github.rojo8399.PlaceholderAPI:api:v4.0`. I can do this in a PR if you want to.

**Comment by Wundero** [comment]
As in, split it into two branches, two package subsystems, or two separate projects? If you could do a simple PR so I can see what you want to see I will try to match all parts of the API that need to be visible to it.

**Comment by Wundero** [comment]
Ok so I have tried testing what you did with Holograms, the `com.github.randombyte-debeloper.holograms:holograms-api:v2.1.1`, and several different iterations of that, and none of them worked. As far as I am concerned, splitting this API into two projects is not worth the time; splitting into two branches goes against how branches should work (as separate versions of the same project); and splitting into two package subsystems offers little to no change. I will likely move the API part of the plugin to its own package, but beyond that I don't believe is necessary nor supported by Jitpack.
