### ISSUE TITLE
Validate method does the wrong thing(copy paste error)

### ISSUE THREAD

**Issue by randombyte-developer** [rojo8399/PlaceholderAPI#29]
Please have a look at: https://github.com/rojo8399/PlaceholderAPI/blob/cd49713e40cc935ed2923479fa9dc6c1ea22bf7f/src/main/java/me/rojo8399/placeholderapi/impl/PlaceholderServiceImpl.java#L140-L145

**Comment by ronaldburns** [comment]
Fixed
