### ISSUE TITLE
PlaceholderAPI Breaks Virtual Chest

### ISSUE THREAD

**Issue by xxsuperdreamxx** [rojo8399/PlaceholderAPI#34]
SpongeAPI version: [spongevanilla-1.10.2-5.2.0-BETA-393](https://www.spongepowered.org/downloads/spongevanilla/stable/1.10.2 )

PlaceholderAPI version:  [PlaceholderAPI v4.1](https://ore.spongepowered.org/rojo8399/PlaceholderAPI/versions/4.1)

Plugins installed:  [Virtual Chest](https://forums.spongepowered.org/t/virtualchest-a-sponge-plugin-which-provides-virtual-chest-guis-for-menus-like-chestcommands/18084)

Error log [if any]: (https://pastebin.com/vLwsuwi6)

Description:  Virtual Chest is using PlaceholderAPI and if you don't use it and open the Menu it doesn't show the name and other placeholders but when I try to open the Menu with PlaceholderAPI it doesn't work. Tried the 1.11.2 and 1.12 versions still doesn't work I remove Nucleus and Nucleus Gluon to see if that breaks the plugins but still doesn't work

**Comment by ronaldburns** [comment]
This sounds like an issue with Virtual Chest
You should contact them, too.

**Comment by xxsuperdreamxx** [comment]
I will

**Comment by Wundero** [comment]
Looks like Virtual Chest is built off of an older version of PlaceholderAPI, so the method it is using is no longer present. The author should update the plugin to match the latest versions of PlaceholderAPI.

**Comment by xxsuperdreamxx** [comment]
Can I ask which version for temporary use

**Comment by Wundero** [comment]
Likely anything below and including 3.12.

**Comment by xxsuperdreamxx** [comment]
Thanks
