### ISSUE TITLE
Ore Sponge Versions

### ISSUE THREAD

**Issue by ryantheleach** [rojo8399/PlaceholderAPI#35]
Would it be possible to add SpongeAPI as a dependency, so it was possible to work out what major version of Sponge PlaceholderAPI was built against or compatible with?

**Comment by Wundero** [comment]
I am not sure what you mean by this. Do you mean in some kind of readme or something? I build PlaceholderAPI for release off of SpongeAPI 5.1 and test it on SpongeAPI 6 and 7 to make sure it maintains compatibility between versions (for the most part, unfortunately Sponge does not support statistics on version 5.1), and the Ore page should reflect the build version.

**Comment by ryantheleach** [comment]
Apologies, seems Ore changed the design of how Sponge API dependencies are shown.

![image](https://user-images.githubusercontent.com/141554/31309543-5d25e6dc-abcf-11e7-9719-72dd4273d46e.png)

**Comment by Wundero** [comment]
No worries, I haven't been checking on Ore in a while. I've been meaning to push an update but school has me swamped.
