### ISSUE TITLE
Problem with statistic 

### ISSUE THREAD

**Issue by Gohu29** [rojo8399/PlaceholderAPI#36]
### Please provide these fields before submitting an issue.

SpongeAPI version: 5.2.0-SNAPSHOT-c675e80

PlaceholderAPI version: 4.1

Plugins (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, PlaceholderAPI

Error log [if any]: (No log error )

Description: 
Connected on server when I try to use `/papi parse GohuSan %player_time_played%`
Plugin response is `ERROR: Player must have statistics!`

I try to enable it with papi enable statistic but nothing change

**Comment by Wundero** [comment]
Statistics only work in Sponge versions 6.0+, since statistics were not implemented in Sponge prior to that update.

There is nothing I can do about this, the only solution is to update your Sponge version.
