### ISSUE TITLE
Config is being reset after server restart

### ISSUE THREAD

**Issue by Krosta8** [rojo8399/PlaceholderAPI#38]
### Please provide these fields before submitting an issue.

SpongeAPI version: 7.0.0

PlaceholderAPI version: 4.2

Plugins installed: 

VirtualChest

Error log [if any]: (please use PasteBin or similar services to shorten error logs)

Description: 
Config of PlaceHolderAPI is same as the default config after server restart.
I changed economy from false to true and after the first server restart is everything okay.
Then, second restart - economy is false again.
I think, that it should be because of server - uptimes. I disabled it and it keeps logging the end-time and start-time of the server. 

Steps to reproduce:
Start Sponge server with economy enabled, restart the server (maybe with the second restart) and economy is disabled again.

**Comment by Wundero** [comment]
Are you changing the config while the server is running? If you are you need to use `/papi reload` to make those changes stick, otherwise they are overwritten on server stop/restart. If you stop the server and change the values, they should stick without the need of the command. If you use the command `/papi enable <x>` it should persist through restarts. I will test that persistence and if it works close this issue.

**Comment by Wundero** [comment]
Oops, not ready to close it yet ;)

**Comment by Krosta8** [comment]
I tried all what you wrote.
I can run /papi reload, but it is not change the settings of enabled/disabled placeholder categories.
I can do /papi enabled (placeholder group) - it works.
Today, after server restart, the same issue appears. The economy placeholders were disabled again. I really don't know why. In the previous version (4.1) was no problem like this.

**Comment by Krosta8** [comment]
Okay, so I tried to do some research and I found out, that the problem is only on API 7.0.0. On API 5.2.0 it is without any problem. I think, that the problem could be repeared for me just by setting economy placeholders on true by default 😄 

In addition, Every placeholders are reseted to the default values after second/third server restart.

**Comment by PixelmonPRO** [comment]
I recently updated with the version 3.12 on version 4.2, and have this problem too. API 5.2.0 (1.10.2-2477-5.2.0-BETA-2731), config economy back to `false` in restart server.
EconomyLite-5.0.0-2.11.0.

**Comment by Wundero** [comment]
This will be fixed in the next update. I figured out what was wrong (and the API version should have nothing to do with it). Not sure when the next release will be because I am super busy but hopefully soon.

**Comment by Wundero** [comment]
Fixed in 4.3.
