### ISSUE TITLE
PlaceholderAPI Incompatable with VirtualChest 4.x

### ISSUE THREAD

**Issue by KhaozFrost** [rojo8399/PlaceholderAPI#42]
### Please provide these fields before submitting an issue.

SpongeAPI version: 
SpongeForge 1.10.2 Latest

PlaceholderAPI version: 

PlaceholderAPI4.2

Plugins installed: 

PlaceholderAPI4.2
VirtualChest4.x

Description: 

Steps to reproduce:

https://github.com/ustc-zzzz/VirtualChest/issues/35#event-1353797251

**Comment by ronaldburns** [comment]
Wonderin has done all the work in the recent updates, so I don't know what could be causing it. I'll be able to take a look at it in an hour or so. Hope to get back to you tonight.

**Comment by ronaldburns** [comment]
Wundero*

**Comment by Wundero** [comment]
When I ran local tests with an economy plugin installed, the economy placeholder worked just fine. In the next update the economy placeholder will no longer disable itself if it cannot find an economy plugin, but instead just not properly parse (and provide a more helpful error tooltip if you use `/papi p <player> %economy_...%`). I will hopefully be fixing any remaining issues with economy in the next update as well but until I narrow down what exactly is happening I cannot confirm anything.

**Comment by Wundero** [comment]
So on API 7 I am having a hard time replicating the issues: with no economy plugin installed, the economy placeholders throw out the error stating that there is no economy plugin; with Total Economy installed (just as a test case), economy placeholders worked. On a fresh install I parsed `balance` (got `100`), `bal_format` (got `$100.00`), and several other placeholders and could not get the placeholders to not parse. 

I think the issue could boil down to two things:
1. There is no installed economy plugin. This one is pretty self-explanatory, an economy plugin needs to be installed for economy placeholders to work. If a player has no money, how can I get how much money they have? ;)
2. The installed economy plugin does not support `EconomyService`. This is an issue you would have to bring up with the author of your economy plugin, as they are not properly making their plugin.

In either case, I could not replicate issues with the placeholder when I had a proper economy plugin installed, so I am not sure what I can do.

**Comment by KhaozFrost** [comment]
EconomyLite-5.0.0-2.12.0.jar
PlaceholderAPI-4.2.jar
VirtualChest v0.4.3

These are the 3 plugins being used so im not to certain what is going on. I made a ticket here and vc but no1 seems to be able to figure it out. but I'm not the only person thats found the incompatibility. with 1.10.2

**Comment by Wundero** [comment]
I ran 4.2 (4.3 but there were no real changes to the economy placeholder so it shouldn't be affected) against Sponge 5.2.0 snapshot c675e804 (1.10.2) and used EconomyLite 2.12.0 and was able to get the placeholders to parse properly. Perhaps the small changes I made will fix this but either way I cannot replicate the issues.
