### ISSUE TITLE
Sponge API Compatibility?

### ISSUE THREAD

**Issue by ghost** [rojo8399/PlaceholderAPI#44]
Hi there, just a quick question - does this plugin work with API 6/7 ?

It looks like it's been updated recently, but it's still listed under API 5 on the release on Ore, and I couldn't find anywhere if it's compatible with API 7. Just want to check before I attempt to install it and possibly break things.

**Comment by Wundero** [comment]
It should be completely compatible with both, as I run my tests on API versions 5, 6 and 7. Of course, if something goes wrong, feel free to throw up an issue here and I will look into resolving it, but it should work as expected on newer versions of the API.
