### ISSUE TITLE
economy placeholder

### ISSUE THREAD

**Issue by shiosakun** [rojo8399/PlaceholderAPI#48]
### Please provide these fields before submitting an issue.

SpongeAPI version: 6.0.0.0

Plugins installed: Total Economy 1.7.1 

Description: when I try to use de %economy_balance_...% with my currency in the Total Economy, it didin´t show me the currency, and shows me as a text, Im doing something wrong? or there isn´t any compatibility with the plugins?

**Comment by Wundero** [comment]
What version of PlaceholderAPI are you using? As well, try typing `/papi parse shiosakun %economy_balance_...%` and seeing what happens - if it has red text, hover over it to see if there are any suggestions or error messages.

**Comment by Wundero** [comment]
Closing this issue as no one has replied about this.
