### ISSUE TITLE
Support for spongeforge-1.12.2-2555-7.1.0-BETA-2831

### ISSUE THREAD

**Issue by smmmadden** [rojo8399/PlaceholderAPI#49]
I'm looking for a PlaceholderAPI & DeluxeJoin that will work on a Sponge Forge Server with spongeforge-1.12.2-2555-7.1.0-BETA-2831 mod and forge-1.12.2-14.23.1.2587.

When I tried with PlaceholderAPI-4.4.jar and DeluxeJoin-5.0.0-1.0.jar the startup fails and server crashes.  Without the PlaceholderAPI, it crashes b/c of the dependency.  Adding it to the startup, I get to the end of startup and then the crash occurs.  See full startup here. https://pastebin.com/ii9UJATa
My guess here is that either or both mods need to be updated to the latest SpongeAPI.

**Comment by ronaldburns** [comment]
I haven't worked on DeluxeJoin in a long time. It was just a quick fun side project.
But, to help you further you'll need to upload the crash report, not the log.

**Comment by Wundero** [comment]
I know that version 4.4 is incompatible with 7.1.0, I am working on an update that will fix it. Unfortunately, I have had almost no time recently so I am not ready to release it yet.

**Comment by Wundero** [comment]
The update is nearing completion, however I noticed that DeluxeJoin is not updated to the latest PlaceholderAPI and thus will not work. I can look into updating it or creating a replacement but, as I said last comment, I am extremely busy so I make no guarantees. You can also use Nucleus' built in [connection messages](https://nucleuspowered.org/docs/modules/connection-messages.html) system, and provided you have [Nucleus Gluon](https://ore.spongepowered.org/dualspiral/Nucleus-Gluon) installed, you can use PlaceholderAPI placeholders. [Nucleus also supports chat messages with placeholders, so you can look into that as well.]
