### ISSUE TITLE
Replace is stripping my colors (return string instead text?)

### ISSUE THREAD

**Issue by FabioZumbi12** [rojo8399/PlaceholderAPI#51]
Hi,

This is not exact an issue but a fix.

I hooked this on my chat plugin (UltimateChat) and on parse my chat messages it only returns Text.
Its ok, but problem is i using coloured `String`s on my parse stage, and because your plugin only returns `Text`, its removing the last color of my string on text conversion, and this is crucial to not happen.

As example, i have a string like `&4[&7MyRank&4]&7`. On conversion to text, its removing (or adding a reset code) and removing that `&7` from my tag.

There is a way to return a string?

Edit: And i added this placeholders to your plugin: https://github.com/FabioZumbi12/UltimateChat/wiki/(9)-PlaceholderAPI-Hook#sponge

**Comment by ronaldburns** [comment]
You're serializing it before parsing it through placeholder api, but it doesn't return any of the color data?

**Comment by FabioZumbi12** [comment]
To be mor specific, this is the way i using: https://github.com/FabioZumbi12/UltimateChat/blob/master/UltimateChat-Sponge-56/src/main/java/br/net/fabiozumbi12/UltimateChat/Sponge/UCMessages.java#L716

I can get the last color tag from my string, but if the color comes from beggining of string, the color dont persist. **I just realized this is because string to text conversion.**

If your plugin makes just the replace using the string by string (without convert to Text) will be fine. Maybe a fourth method to handle string to string?

Thanks for attention.

Edit.: Oh, and a thing where i dont how to do. On bukkit's papi we can add some variables to placeholder name like `%plugin_tag_<my_variable>%`. How can i do this with your plugin? This variable can change according player inputs or configurations.

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1504
