### ISSUE TITLE
Request - Add non admin command or subdivide perms.

### ISSUE THREAD

**Issue by Lorrainrm** [rojo8399/PlaceholderAPI#52]
Is just a suggestion:
It'd be awesome to allow an admin to parse a placeholder and it return to a defined player.
Usefull for setting custom commands.

Or, if not possible, subdivide the permissions so i could give placeholderapi.admin.parse for a player instead of the whole placeholderapi.admin

:)

**Comment by ronaldburns** [comment]
Keeping open until next release

**Comment by Lorrainrm** [comment]
Sounds good!
Thanks !

**Comment by Lorrainrm** [comment]
Any ETA of the next version? *-*
