### ISSUE TITLE
Exception while parse player's statistic value

### ISSUE THREAD

**Issue by Tollainmear** [rojo8399/PlaceholderAPI#53]
### Please provide these fields before submitting an issue.

SpongeAPI version: 5.2.0-SNAPSHOT-c675e80

PlaceholderAPI version: 4.4

Plugins installed: 

Error log [if any]:  [Gist](https://gist.github.com/Tollainmear/d48122aa09bea202a9e113ab90a4c92a)

Description: Exception while parse player's statistic value

Steps to reproduce:
    1.player is online
    2.Command “/papi parse Tollainmear %player_time_played%” I ran.
    3.Exception shown as [Gist](https://gist.github.com/Tollainmear/d48122aa09bea202a9e113ab90a4c92a)

**Comment by Wundero** [comment]
Statistics are not implemented on Sponge API 5.X. Upgrade to 6.0+ for statistics.
