### ISSUE TITLE
Spams this error. Kicks players.

### ISSUE THREAD

**Issue by KyleFreedomSeeds** [rojo8399/PlaceholderAPI#54]
### Please provide these fields before submitting an issue.

SpongeAPI version: 7.1 2931

PlaceholderAPI version: 4.4

Plugins installed: [nucleus-info-20180313-153804.txt](https://github.com/rojo8399/PlaceholderAPI/files/1816097/nucleus-info-20180313-153804.txt)

Error log [if any]: https://gyazo.com/a1b7424a3cadf4b16d4137dbbe698d12 

Description: Every so often, this error will get spammed and will kick players saying "A Fatal error has occurred. The connection has been terminated"

Steps to reproduce: Unknown. Occurred after we updated a core mod. Pixelmon Reforged from 6.2.1 to 6.2.2

**Comment by ronaldburns** [comment]
For future notes, we prefer copy and pasted logs just so we can ctrl+f find specific things.
Although skimming through this, nothing seems to specifically point towards PlaceholderAPI.
Does it only happen with the plugin installed?

**Comment by Wundero** [comment]
This looks like an issue with Pixelmon, not PlaceholderAPI. Consult the Pixelmon devs with this issue, they should be able to help you.
