### ISSUE TITLE
Config Invalid! on load.

### ISSUE THREAD

**Issue by iEatNoodlez** [rojo8399/PlaceholderAPI#62]
SpongeAPI version: Sponge Forge / 7.1.0-70763aa8 / 1.12.2-2768-7.1.4

PlaceholderAPI version: 4.5.1

Plugins installed: Installed on Sky Adventures 1.3.0 Server
- CommandsUtils
- Holograms
- LuckPerms
- PlaceholderAPI
- ServerListPlus
- WorldEdit

Error log [if any]: https://pastebin.com/b17J1vUk

Description: Getting error about config Invalid on load and every time after reload. 

Steps to reproduce: Mystery. Started from blank configuration on Sky Adventure 1.3.0 Server.

**Comment by iEatNoodlez** [comment]
Nevermind, same issue persist with #61 . Using @randombyte-developer 's fix. Closing.

**Comment by randombyte-developer** [comment]
@rojo8399 Maybe you could recompile the plugin?
