### ISSUE TITLE
%player_displayname% has incorrect replacement

### ISSUE THREAD

**Issue by TheBrambleShark** [rojo8399/PlaceholderAPI#64]
### Please provide these fields before submitting an issue.

SpongeAPI version: 7.1.0-366290f8
PlaceholderAPI version: 4.5.1

Expected behavior:
The replacement `%player_displayname%` should render as the player's nickname or else fall back to their username if no such name is present.

Actual behavior:
As seen in this screenshot, `%player_displayname%` shows the user's username, despite a nickname being set.
![image](https://user-images.githubusercontent.com/7003081/53467110-4c967400-3a1a-11e9-93d6-750738f7c968.png)

This issue is made visible through the use of TabManager. Please see the [sister issue](https://github.com/Proxying/TabManager/issues/17) for more information.

**Comment by randombyte-developer** [comment]
Where did you set the nickname?

**Comment by TheBrambleShark** [comment]
@randombyte-developer This was set using the `/nick` command provided by Nucleus. I've attached a screenshot to show the output of `/lp verbose` to confirm this.
![2019-02-27_15 49 04](https://user-images.githubusercontent.com/7003081/53525410-54e8c080-3aa7-11e9-876e-aada86b8599a.png)

**Comment by randombyte-developer** [comment]
Maybe https://ore.spongepowered.org/dualspiral/Nucleus-Gluon helps?

**Comment by TheBrambleShark** [comment]
I've installed Gluon, but as I'd expected, I didn't think it would work. Gluon allows you to use PlaceholderAPI replacements in Nucleus and adds Nucleus replacements to PlaceholderAPI. However, I do believe that `%player_displayname%` gets the display name component from Sponge or perhaps even the underlying Minecraft (forge) server. Nucleus just exposes a command to be able to configure your nickname.

Upon joining the server, chatted to show I have a nickname set and ran the `/papi parse` command. You can see the output of this below:
![image](https://user-images.githubusercontent.com/7003081/53526912-15bc6e80-3aab-11e9-9755-40f590a47271.png)

**Comment by TheBrambleShark** [comment]
So using the placeholder `%nucleus_displayname%` works, though this has a bit of a design smell imho. I'm following up with the Nucleus team now to find out why they're not passing this data through the `%player_displayname%` replacement and instead building in their own and having you use a bridge plugin to support it.

I'll go ahead and close this issue for now, since there is a viable work-around.
