### ISSUE TITLE
Further expansion

### ISSUE THREAD

**Issue by Wundero** [rojo8399/PlaceholderAPI#7]
This is more of a checklist/brainstorm than an issue, but I think some things could be added to allow more dynamic and powerful placeholders.

- [x] Configurable expansions (Configuration grabbed from PlaceholderAPI plugin)
- [x] Relational placeholders
- [x] Custom delimiters for regular expression
- [x] Javascript Placeholders
- [x] `Text` instead of `String` for better Sponge integration
- [x] [bStats](https://forums.spongepowered.org/t/bstats-a-modern-alternative-to-mcstats/16065) support
- [ ] Online file explorer (GH Pages?) for scripts/expansions
  - [ ] JavaScript+HTML backend (Not sure how well I can do this since I don't know much JS or HTML)
  - [ ] GitHub Pages enabled
- [x] Internaltionalization
~~Removed injection systems~~ Not in the domain of the plugin.
~~Multiple versions for Sponge builds is not valuable~~ Might as well stay on latest, once api 8 rolls out this will move to 8 exclusivity anyways. Latest is greatest ;)
~~ValueModifiers~~ I've realized that this is not particularly helpful as you can execute fill methods now. Since retrieving real values for placeholders, like `Integer`, `List`, etc. instead of just `Text` is now possible and easy this has become significantly more niche, if not downright useless. 

Feel free to leave a comment suggesting a feature. If you want to request a placeholder, see #12 instead.

**Comment by Wundero** [comment]
I am heavily considering a cloud expansion system, for both Expansion implementation classes and/or JavaScript scripts, but I am unsure about what the best way to do that would be. 

One option could be to use GitHub Pages to provide a sort of "file explorer" for these files; you can peruse scripts or classes and then download them as you please. This is helpful because it allows you to show the users the code if they want to see it, and it is not a download that they are not initializing. However this does have the caveat of not automatically installing in the right directory for expansions or scripts, and is also not quite as intuitive as an in game browser would be. Another issue with this, although temporary, is that I do not know how to write such a system because I only know Java.

Another option is to have an automatic downloader for scripts or expansions. This could access some form of file host and download the files on command. This is a good option for ease of use, because it would allow an in game system for browsing and downloading expansions. However, this has some security issues that I am unsure about how to solve: the large possibility of downloading and running malicious code without knowing that you have done so causes these issues to arise, and I don't particularly know how to deal with them. An option is to sandbox test the code, but that consumes machine resources and I also do not know how to do it. There are other issues with this system as well: the inability to view code or test examples without downloading the placeholder, the large structure of classes necessary to fully implement the cloud downloader, and the lack of having a proper download source (meaning I cannot access things like version, author, or other metadata without downloading the whole file).

I am quite likely to opt for the "file explorer" version simply because I think it would be a more elegant solution, and it doesn't have the security flaws the other solution has, but I am open to suggestions.

**Comment by ronaldburns** [comment]
I like the file explorer option. The built in one in Spigot's PlaceholderAPI is a hassle to find the correct names/ids of each expansion, then typing each command to download them.

**Comment by Wundero** [comment]
@rojo8399 Do you have any more ideas before I push the update?

**Comment by ronaldburns** [comment]
Only localization, but that should be its own update.

**Comment by Wundero** [comment]
I did localization, to an extent, already. I have not created translations for other languages however I have allowed complete customization of messages so all that is left is to add additional translations.

**Comment by Wundero** [comment]
This issue is no longer useful, as pretty much everything I want has either been achieved or probably won't need to be. As for the "file browser" thing, I probably won't pursue it at all. This plugin should be used as an API, so what I would prefer to do is build support into other plugins for this instead.
